version: "3.8"

services:
  apache:
    build: ./php
    container_name: somnia_apache
    restart: always
    environment:
      - DB_HOST=somnia
      - DB_USER=somnia
      - DB_PASSWORD=somnia
      - DB_NAME=somnia
    volumes:
      - ../:/var/www/html
    ports:
      - 8080:80
    links:
      - database
  
  database:
    container_name: database
    image: mariadb:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: somnia
      MYSQL_USER: somnia
      MYSQL_PASSWORD: somnia159753
    volumes:
     - ./mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 9090:80
    environment:
      - PMA_HOST=database
      - PMA_USER=somnia
      - PMA_PASSWORD=somnia159753
      - MYSQL_ROOT_PASSWORD=root